### ISSUE TITLE
Building New Server

### ISSUE THREAD

**Issue by jimthedj65** [diodechain/diode_server_ex#19]
Hi All,  
I am running vagrant with ubuntu-bionic-18.04. I updated my dev environment with the required make etc I installed esl-erlang as follows:
Add Erlang Solutions repository: wget https://packages.erlang-solutions.com/erlang-solutions_2.0_all.deb && sudo dpkg -i erlang-solutions_2.0_all.deb
Run: sudo apt-get update
Install the Erlang/OTP platform and all of its applications: sudo apt-get install esl-erlang
Install Elixir: sudo apt-get install elixir

mix deps.get shows the following:
Resolving Hex dependencies...
Dependency resolution completed:
Unchanged:
  benchee 1.0.1
  cowboy 1.1.2
  cowlib 1.0.2
  debouncer 0.1.3
  decimal 1.8.1
  deep_merge 1.0.0
  earmark 1.4.4
  elixir_make 0.6.0
  esqlite 0.4.1
  ex_doc 0.21.3
  keccakf1600_orig 2.0.0
  libsecp256k1 0.1.10
  makeup 1.0.1
  makeup_elixir 0.14.0
  mime 1.3.1
  mix_erlang_tasks 0.1.0
  nimble_parsec 0.5.3
  plug 1.10.0
  plug_cowboy 1.0.0
  plug_crypto 1.1.2
  poison 3.1.0
  profiler 0.2.2
  ranch 1.3.2
  while 0.2.2
All dependencies are up to date

when running mix compile a number of issues show up:

mix compile
warning: variable "description" does not exist and is being expanded to "description()", please use parentheses to remove the ambiguity or change the variable name
  /home/vagrant/diode_server_ex/deps/mix_erlang_tasks/mix.exs:9: MixErlangTasks.Mixfile.project/0

warning: variable "package" does not exist and is being expanded to "package()", please use parentheses to remove the ambiguity or change the variable name
  /home/vagrant/diode_server_ex/deps/mix_erlang_tasks/mix.exs:10: MixErlangTasks.Mixfile.project/0

==> mix_erlang_tasks
Compiling 4 files (.ex)
warning: :ct.run_test/1 defined in application :common_test is used by the current application but the current application does not directly depend on :common_test. To fix this, you must do one of:

  1. If :common_test is part of Erlang/Elixir, you must include it under :extra_applications inside "def application" in your mix.exs

  2. If :common_test is a dependency, make sure it is listed under "def deps" in your mix.exs

  3. In case you don't want to add a requirement to :common_test, you may optionally skip this warning by adding [xref: [exclude: :ct]] to your "def project" in mix.exs

  lib/mix/tasks/ct.ex:30: Mix.Tasks.Ct.run/1

warning: :edoc.application/3 defined in application :edoc is used by the current application but the current application does not directly depend on :edoc. To fix this, you must do one of:

  1. If :edoc is part of Erlang/Elixir, you must include it under :extra_applications inside "def application" in your mix.exs

  2. If :edoc is a dependency, make sure it is listed under "def deps" in your mix.exs

  3. In case you don't want to add a requirement to :edoc, you may optionally skip this warning by adding [xref: [exclude: :edoc]] to your "def project" in mix.exs

  lib/mix/tasks/edoc.ex:8: Mix.Tasks.Edoc.run/1

warning: :eunit.test/2 defined in application :eunit is used by the current application but the current application does not directly depend on :eunit. To fix this, you must do one of:

  1. If :eunit is part of Erlang/Elixir, you must include it under :extra_applications inside "def application" in your mix.exs

  2. If :eunit is a dependency, make sure it is listed under "def deps" in your mix.exs

  3. In case you don't want to add a requirement to :eunit, you may optionally skip this warning by adding [xref: [exclude: :eunit]] to your "def project" in mix.exs

  lib/mix/tasks/eunit.ex:32: Mix.Tasks.Eunit.run/1

warning: String.to_char_list/1 is deprecated. Use String.to_charlist/1 instead
Found at 2 locations:
  lib/mix/tasks/ct.ex:31: Mix.Tasks.Ct.run/1
  lib/mix/tasks/ct.ex:32: Mix.Tasks.Ct.run/1

warning: String.to_char_list/1 is deprecated. Use String.to_charlist/1 instead
Found at 2 locations:
  lib/util.ex:13: MixErlangTasks.Util.compile_files/2
  lib/util.ex:14: MixErlangTasks.Util.compile_files/2

Generated mix_erlang_tasks app
==> Elixir.Diode
Could not find "rebar3", which is needed to build dependency :esqlite
I can install a local copy which is just used by Mix
Shall I install rebar3? (if running non-interactively, use "mix local.rebar --force") [Yn] Y
* creating /home/vagrant/.mix/rebar
* creating /home/vagrant/.mix/rebar3
===> Fetching pc v1.11.0
===> Downloaded package, caching at /home/vagrant/.cache/rebar3/hex/hexpm/packages/pc-1.11.0.tar
===> Compiling pc
===> Compiling esqlite
===> Compiling c_src/esqlite3_nif.c
===> Compiling c_src/queue.c
===> Compiling c_src/sqlite3/sqlite3.c
===> Linking /home/vagrant/diode_server_ex/deps/esqlite/priv/esqlite3_nif.so
c_src/build_deps.sh
Cloning into 'secp256k1'...
remote: Enumerating objects: 88, done.
remote: Counting objects: 100% (88/88), done.
remote: Compressing objects: 100% (86/86), done.
remote: Total 6007 (delta 10), reused 15 (delta 0), pack-reused 5919
Receiving objects: 100% (6007/6007), 2.66 MiB | 5.49 MiB/s, done.
Resolving deltas: 100% (4161/4161), done.
HEAD is now at d333521 Merge #494: Support OpenSSL versions >= 1.1 for ENABLE_OPENSSL_TESTS
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'build-aux'.
libtoolize: copying file 'build-aux/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'build-aux/m4'.
libtoolize: copying file 'build-aux/m4/libtool.m4'
libtoolize: copying file 'build-aux/m4/ltoptions.m4'
libtoolize: copying file 'build-aux/m4/ltsugar.m4'
libtoolize: copying file 'build-aux/m4/ltversion.m4'
libtoolize: copying file 'build-aux/m4/lt~obsolete.m4'
configure.ac:10: installing 'build-aux/compile'
configure.ac:5: installing 'build-aux/config.guess'
configure.ac:5: installing 'build-aux/config.sub'
configure.ac:9: installing 'build-aux/install-sh'
configure.ac:9: installing 'build-aux/missing'
Makefile.am: installing 'build-aux/depcomp'
parallel-tests: installing 'build-aux/test-driver'
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking how to print strings... printf
checking for style of include used by make... GNU
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking for a sed that does not truncate output... /bin/sed
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for fgrep... /bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /bin/dd
checking how to truncate binary pipes... /bin/dd bs=4096 count=1
checking for mt... mt
checking if mt is a manifest tool... no
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking whether make supports nested variables... (cached) yes
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for ar... /usr/bin/ar
checking for ranlib... /usr/bin/ranlib
checking for strip... /usr/bin/strip
checking for gcc... gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... (cached) none needed
checking whether gcc understands -c and -o together... (cached) yes
checking dependency style of gcc... (cached) gcc3
checking how to run the C preprocessor... gcc -E
checking for gcc option to accept ISO C89... (cached) none needed
checking dependency style of gcc... gcc3
checking if gcc supports -std=c89 -pedantic -Wall -Wextra -Wcast-align -Wnested-externs -Wshadow -Wstrict-prototypes -Wno-unused-function -Wno-long-long -Wno-overlength-strings... yes
checking if gcc supports -fvisibility=hidden... yes
checking for __int128... yes
checking for __builtin_expect... yes
checking native compiler: gcc... ok
checking for x86_64 assembly availability... yes
checking gmp.h usability... no
checking gmp.h presence... no
checking for gmp.h... no
checking for CRYPTO... no
checking openssl/crypto.h usability... no
checking openssl/crypto.h presence... no
checking for openssl/crypto.h... no
checking for javac... no
configure: WARNING: cannot find JDK; try setting $JAVAC or $JAVA_HOME
checking jni headers... none
configure: WARNING: jni headers/dependencies not found. jni support disabled
checking whether byte ordering is bigendian... no
configure: Using static precomputation: yes
configure: Using assembly optimizations: x86_64
configure: Using field implementation: 64bit
configure: Using bignum implementation: no
configure: Using scalar implementation: 64bit
configure: Using endomorphism optimizations: no
configure: Building benchmarks: yes
configure: Building for coverage analysis: no
configure: Building ECDH module: no
configure: Building ECDSA pubkey recovery module: yes
configure: Using jni: no
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating libsecp256k1.pc
config.status: creating src/libsecp256k1-config.h
config.status: executing depfiles commands
config.status: executing libtool commands
make[1]: Entering directory '/home/vagrant/diode_server_ex/deps/libsecp256k1/c_src/secp256k1'
gcc -I. -g -O2 -Wall -Wextra -Wno-unused-function -c src/gen_context.c -o gen_context.o
gcc gen_context.o -o gen_context
./gen_context
  CC       src/libsecp256k1_la-secp256k1.lo
  CCLD     libsecp256k1.la
/usr/bin/ar: `u' modifier ignored since `D' is the default (see `U')
  CC       src/bench_verify.o
  CCLD     bench_verify
  CC       src/bench_sign.o
  CCLD     bench_sign
  CC       src/bench_internal-bench_internal.o
  CCLD     bench_internal
  CC       src/bench_ecmult-bench_ecmult.o
  CCLD     bench_ecmult
  CC       src/tests-tests.o
  CCLD     tests
  CC       src/exhaustive_tests-tests_exhaustive.o
  CCLD     exhaustive_tests
  CC       src/bench_recover.o
  CCLD     bench_recover
make[1]: Leaving directory '/home/vagrant/diode_server_ex/deps/libsecp256k1/c_src/secp256k1'
cc -I/usr/lib/erlang/erts-11.1.4/include -I c_src/secp256k1 -I c_src/secp256k1/src -I c_src/secp256k1/include -I../libsecp256k1/src -fPIC -shared -o priv/libsecp256k1_nif.so c_src/libsecp256k1_nif.c c_src/secp256k1/.libs/libsecp256k1.a -lgmp
c_src/libsecp256k1_nif.c: In function ‘ecdsa_sign’:
c_src/libsecp256k1_nif.c:494:51: warning: passing argument 2 of ‘secp256k1_ecdsa_signature_serialize_der’ from incompatible pointer type [-Wincompatible-pointer-types]
  if (secp256k1_ecdsa_signature_serialize_der(ctx, &intermediatesig, &siglen, &signature) != 1) {
                                                   ^
In file included from c_src/libsecp256k1_nif.c:9:0:
c_src/secp256k1/src/secp256k1.c:261:5: note: expected ‘unsigned char *’ but argument is of type ‘unsigned char (*)[74]’
 int secp256k1_ecdsa_signature_serialize_der(const secp256k1_context* ctx, unsigned char *output, size_t *outputlen, const secp256k1_ecdsa_signature* sig) {
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from c_src/secp256k1/src/secp256k1.c:9:0,
                 from c_src/libsecp256k1_nif.c:9:
c_src/libsecp256k1_nif.c:497:64: warning: passing argument 3 of ‘secp256k1_ecdsa_signature_parse_der’ from incompatible pointer type [-Wincompatible-pointer-types]
     CHECK(secp256k1_ecdsa_signature_parse_der(ctx, &signature, &intermediatesig, siglen) == 1);
                                                                ^
c_src/secp256k1/src/util.h:40:39: note: in definition of macro ‘EXPECT’
 #define EXPECT(x,c) __builtin_expect((x),(c))
                                       ^
c_src/libsecp256k1_nif.c:497:5: note: in expansion of macro ‘CHECK’
     CHECK(secp256k1_ecdsa_signature_parse_der(ctx, &signature, &intermediatesig, siglen) == 1);
     ^~~~~
In file included from c_src/libsecp256k1_nif.c:9:0:
c_src/secp256k1/src/secp256k1.c:224:5: note: expected ‘const unsigned char *’ but argument is of type ‘unsigned char (*)[74]’
 int secp256k1_ecdsa_signature_parse_der(const secp256k1_context* ctx, secp256k1_ecdsa_signature* sig, const unsigned char *input, size_t inputlen) {
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/bin/ld: cannot find -lgmp
collect2: error: ld returned 1 exit status
make: *** [priv/libsecp256k1_nif.so] Error 1
Makefile:30: recipe for target 'priv/libsecp256k1_nif.so' failed
==> libsecp256k1
warning: Mix compiler :make_bindings was supposed to return {:ok | :noop | :error, [diagnostic]} but it returned :error
Compiling 1 file (.erl)
src/libsecp256k1.erl:146: Warning: function not_loaded/1 is unused
Generated libsecp256k1 app
==> nimble_parsec
Compiling 4 files (.ex)
Generated nimble_parsec app
==> makeup
Compiling 44 files (.ex)
Generated makeup app
===> Compiling ranch
src/ranch_ssl.erl:128: Warning: ssl:ssl_accept/2 is deprecated and will be removed in OTP 24; use use ssl_handshake/1,2,3 instead
src/ranch_ssl.erl:233: Warning: ssl:cipher_suites/0 is deprecated and will be removed in OTP 24; use use cipher_suites/2,3 instead
src/ranch_ssl.erl:235: Warning: ssl:cipher_suites/0 is deprecated and will be removed in OTP 24; use use cipher_suites/2,3 instead

==> decimal
Compiling 1 file (.ex)
Generated decimal app
warning: String.strip/1 is deprecated. Use String.trim/1 instead
  /home/vagrant/diode_server_ex/deps/poison/mix.exs:4: Poison.Mixfile

==> poison
Compiling 4 files (.ex)
warning: Integer.to_char_list/2 is deprecated. Use Integer.to_charlist/2 instead
  lib/poison/encoder.ex:173: Poison.Encoder.BitString.seq/1

Generated poison app
===> Compiling keccakf1600
make: Entering directory '/home/vagrant/diode_server_ex/deps/keccakf1600/c_src'
 C      decaf-utils.c
 C      keccakf1600_nif.c
 C      shake.c
In file included from /usr/include/assert.h:35:0,
                 from /home/vagrant/diode_server_ex/deps/keccakf1600/c_src/shake.c:43:
/usr/include/features.h:184:3: warning: #warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE" [-Wcpp]
 # warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE"
   ^~~~~~~
 LD     keccakf1600.so
/usr/bin/ld: cannot find -lerl_interface
collect2: error: ld returned 1 exit status
Makefile:140: recipe for target '/home/vagrant/diode_server_ex/deps/keccakf1600/c_src/../priv/keccakf1600.so' failed
make: *** [/home/vagrant/diode_server_ex/deps/keccakf1600/c_src/../priv/keccakf1600.so] Error 1
make: Leaving directory '/home/vagrant/diode_server_ex/deps/keccakf1600/c_src'
===> Hook for compile failed!

==> Elixir.Diode
** (Mix) Could not compile dependency :keccakf1600, "/home/vagrant/.mix/rebar3 bare compile --paths /home/vagrant/diode_server_ex/_build/dev/lib/*/ebin" command failed. You can recompile this dependency with "mix deps.compile keccakf1600", update it with "mix deps.update keccakf1600" or clean it with "mix deps.clean keccakf1600"

I have tried rebuilding this environment a few times and this is the furthest I have managed to reach, any help in resolving these issues during compile would be appreciated.

**Comment by dominicletz** [comment]
Thanks @jimthedj65 this has been fixed by 0c64b8cb787e15019fdd12bd6ddaba83b035ece9

**Comment by jimthedj65** [comment]
thanks, I have my bare-metal server and will attempt to install this again.
