### ISSUE TITLE
Replace camelcase function names with snake case

### ISSUE THREAD

**Issue by dominicletz** [diodechain/diode_server_ex#2]
Following Elixir conventions (https://github.com/elixir-lang/elixir/blob/master/lib/elixir/pages/Naming%20Conventions.md) 

```
some_map = %{this_is_a_key: "and a value"}
is_map(some_map)
```

**Comment by zpeters** [comment]
I will work on this one

**Comment by dominicletz** [comment]
Mostly done at this time.
