### ISSUE TITLE
travis ci test failed

### ISSUE THREAD

**Issue by zpeters** [diodechain/diode_server_ex#6]
I forked the repo to do some work on a few issues.  Before i started work i ran a test with travis ci and noticed it failed.  I checked your main repo and see that it passed.  Comparing the commit number they appear to be the same.  Any idea with one would pass and one would fail?

https://travis-ci.com/diodechain/diode_server_ex/builds/132564713

https://travis-ci.com/zpeters/diode_server_ex/builds/132659582

**Comment by dominicletz** [comment]
Thanks, indeed there was a timing issue that made it fail *sometimes*
